# Generated by Django 6.0.4 on 2026-04-18 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('regression', 'Regression'), ('classification', 'Classification'), ('clustering', 'Clustering')], max_length=20)),
                ('model_name', models.CharField(choices=[('linear_regression', 'Linear Regression'), ('ridge', 'Ridge Regression'), ('lasso', 'Lasso Regression'), ('decision_tree_reg', 'Decision Tree (Regression)'), ('random_forest_reg', 'Random Forest (Regression)'), ('logistic_regression', 'Logistic Regression'), ('decision_tree_cls', 'Decision Tree (Classification)'), ('random_forest_cls', 'Random Forest (Classification)'), ('svm_cls', 'SVM (Classification)'), ('knn_cls', 'KNN (Classification)'), ('kmeans', 'K-Means Clustering'), ('dbscan', 'DBSCAN Clustering')], max_length=30)),
                ('input_columns', models.JSONField(default=list)),
                ('output_column', models.CharField(blank=True, max_length=200)),
                ('parameters', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('predictions', models.JSONField(default=list)),
                ('chart_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_results', to='datasets.dataset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_results', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
